package it.pccube.batchmigration.costant;

public class Constants {

	public static final String BATCH_USER = "BATCH_MIGRATION";
	
	public static final String SELECT_FE_LOG_ERRORE_BATCH_DB = "SELECT CODICE_ERRORE, DATA, DESCRIZIONE_ERRORE, ID_LOG_ERRORE_BATCH_DB, NOTE, PACKAGE AS PACKAGE_, PROCEDURA FROM FE_LOG_ERRORE_BATCH_DB";
	
	public static final String SELECT_FE_LOG_ESECUZIONE_BATCH_DB = "SELECT DATA_FINE_ESECUZIONE, DATA_INIZIO_ESECUZIONE, ERRORE_ESECUZIONE, ID_LOG_ESECUZIONE_BATCH_DB, NUM_ELEMENTI_COMPLESSIVI, NUM_ELEMENTI_ELABORATI, PACKAGE AS PACKAGE_, PROCEDURA FROM FE_LOG_ESECUZIONE_BATCH_DB";
	
}
